## Data Analysis and Visualisation

**Name - Harsh Bamotra** <br>
**Roll No. - AC-1216**

In [90]:
import numpy as np

**Q1. Given below is a dictionary having two keys ‘Boys’ and ‘Girls’ and having two lists of heights of five Boys andFive Girls respectively as values associated with these keys. Original dictionary of lists: <br><br>
{'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]} <br><br>
From the given dictionary of lists create the following list of dictionaries: <br>
[{'Boys': 72, 'Girls': 63}, {'Boys': 68, 'Girls': 65}, {'Boys': 70, 'Girls': 69}, {'Boys': 69, 'Girls': 62}, {‘Boys’:74,‘Girls’:61]**

In [1]:
D1 = {'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]}

In [7]:
L1 = []
for i in range(len(D1["Boys"])):
    L1.append({'Boys':D1["Boys"][i], 'Girls':D1["Girls"][i]})
L1

[{'Boys': 72, 'Girls': 63},
 {'Boys': 68, 'Girls': 65},
 {'Boys': 70, 'Girls': 69},
 {'Boys': 69, 'Girls': 62},
 {'Boys': 74, 'Girls': 61}]

**Q2. Given are three lists where L1 has names of n students, L2 has marks and L3 has hobbies   of n students.Using three lists, create the following dictionary with hobbies as keys and (names,marks) as values. In case more than one student has same hobby then values must be appended for the same key instead of overwriting.E.g.<br><br>
L1=['A','B','C'], L2=[100,40,50] L3=['painting','music','painting']<br>
then output should be:<br>
dict1={painting:(('A',100),('C',50)), 'music':('B',40)}.**

In [56]:
def Hobbies(l1, l2, l3):
    result = {}
    for i in range(len(l1)):
        if(l3[i] not in result):
            result[l3[i]] = (l1[i], l2[i])
        elif(len(result[l3[i]][0]) == 1):
            t = result[l3[i]]
            l = []
            l.append(t)
            l.append((l1[i], l2[i]))
            result[l3[i]] = tuple(l)
        else:
            l = list(result[l3[i]])
            l.append((l1[i], l2[i]))
            result[l3[i]] = tuple(l)
    return result

In [58]:
print(Hobbies(['A','B','C', 'D', 'E'], [100,40,50,60,70], ['painting','music','painting','painting','music']))

{'painting': (('A', 100), ('C', 50), ('D', 60)), 'music': (('B', 40), ('E', 70))}


**Q3. Write  two  lambda functions <br> 
a)One to  arrange a list of names on the last letter of the name. <br>     
i.e. names=['axc','bxbb','xxb','zzxy','zzc'] then new sorted list on last letter  is ['bxbb', 'xxb', 'axc', 'zzc', 'zzxy']**

In [77]:
l = eval(input("Enter the list ::"))
l.sort(key = lambda l: l[-1])
print("The list after sorting ::", l)

Enter the list ::['axc','bxbb','xxb','zzxy','zzc']
The list after sorting :: ['bxbb', 'xxb', 'axc', 'zzc', 'zzxy']


**b)Second lambda function arranges list on the length of names and store results in dictionary with length as key and value as names.**

In [97]:
l = eval(input("Enter the list ::"))
l.sort(key = lambda l: len(l))
d = {}
for i in range(len(l)):
    d[len(l[i])] = [lambda l: l[i] if(len(l[i]) not in d) else list(d[len(l[i])]).append(l[i])]
print("The new dictonary ::", d)

Enter the list ::['axc','bxbb','xxb','zzxy','zzc']
The new dictonary :: {3: [<function <lambda> at 0x00000140C9248820>], 4: [<function <lambda> at 0x00000140C932F0A0>]}


**Q4. Write programs in Python using NumPy library to do the following: <br>
a) Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis.**

In [96]:
arr = np.arange(9).reshape(3, 3)
print("Mean ::", np.mean(arr, axis = 1))
print("Standard deviation ::", np.std(arr, axis = 1))
print("Variance ::", np.var(arr, axis = 1))

Mean :: [1. 4. 7.]
Standard deviation :: [0.81649658 0.81649658 0.81649658]
Variance :: [0.66666667 0.66666667 0.66666667]


**b) Get the indices of the sorted elements of a given array.<br>B= [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]**

In [101]:
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
print("The indices of the sorted list are ::", np.argsort(B))

The indices of the sorted list are :: [8 2 6 9 3 7 1 0 4 5]


**c) Create a 2-dimensional array of size m x n integer elements, also print the shape, type and datatype of the array and then reshape it into nx m array, n and m are user inputs given at the run time.**

In [107]:
n = int(input("Enter the value of n ::"))
m = int(input("Enter the value of m ::"))
arr = np.arange(n*m).reshape(n, m)
print("The random array :\n", arr)
print("Shape ::", arr.shape, "\nType ::", type(arr), "\nDatatype ::", type(arr[0][0]))

Enter the value of n ::4
Enter the value of m ::5
The random array :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Shape :: (4, 5) 
Type :: <class 'numpy.ndarray'> 
Datatype :: <class 'numpy.int32'>


In [110]:
arr = arr.reshape(m, n)
print("The array after reshaping ::\n", arr)

The array after reshaping ::
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


**d) Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays.**

In [113]:
arr = eval(input("Enter the array ::"))
Zero =[]
Non_Zero = [] 
NAN = []
for i in range(len(arr)):
    if(arr[i] == 0):
        Zero.append(i)
    elif(arr[i] == None):
        NAN.append(i)
    else:
        Non_Zero.append(i)
print("Indices of zero elements ::", Zero, "\nIndices of non-zero elements ::", Non_Zero, "\nIndices of NaN elements ::", NAN)

Enter the array ::[1, 2, 0, 6, 0, None]
Indices of zero elements :: [2, 4] 
Indices of non-zero elements :: [0, 1, 3] 
Indices of NaN elements :: [5]


**Q5. Generate a 2D array having values from 1 to 100  of shape (4,5).**

In [143]:
arr = np.array(np.random.randint(1, 101, size=(4, 5)))
print("The randomly genrated array\n", arr)

The randomly genrated array
 [[26 42 60 44 69]
 [48 19 81 55 49]
 [58 18 56  4 43]
 [60 32 75 17 75]]


**I) Multiply all elements that are greater than 50 by 2.**

In [147]:
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if(arr[i][j] > 50):
            arr[i][j]*=2
print(arr)

[[ 26  42 120  44 138]
 [ 48  19 162 110  49]
 [116  18 112   4  43]
 [120  32 150  17 150]]


**II) Extract 2x2  lower-right matrix from the given array and find its largest element.** 

In [157]:
arr1 = arr[2: , 3:]
print("New 2x2 array ::\n",arr1)
print("Largest element ::", np.amax(arr1))

New 2x2 array ::
 [[  4  43]
 [ 17 150]]
Largest element :: 150
